# Generated by Django 4.0.3 on 2022-08-02 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('palabras_clave', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=300)),
                ('cuenta_respuestas', models.BigIntegerField(default=0)),
                ('eleccion', models.CharField(default='null', max_length=20)),
                ('umbral_eleccion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fiabilidad_opcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captchaprot.coleccion')),
            ],
        ),
        migrations.CreateModel(
            name='Clave_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=32)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opciones_reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=20)),
                ('cuenta', models.BigIntegerField(default=0)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captchaprot.reto')),
            ],
            options={
                'unique_together': {('reto', 'opcion')},
            },
        ),
    ]
