# Generated by Django 4.0.3 on 2022-03-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captchaprot', '0002_remove_answer_id_alter_answer_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
    ]
