# Generated by Django 4.0.3 on 2022-03-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaprot', '0003_rename_question_id_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('option1', models.CharField(max_length=15)),
                ('rate1', models.BigIntegerField()),
                ('option2', models.CharField(max_length=15)),
                ('rate2', models.BigIntegerField()),
                ('option3', models.CharField(max_length=15)),
                ('rate3', models.BigIntegerField()),
                ('choice', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
