# Generated by Django 4.0.3 on 2022-03-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaprot', '0004_challenges_delete_answer_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='choiceRatio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='choice',
            field=models.CharField(default='ND', max_length=15),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='rate1',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='rate2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='rate3',
            field=models.BigIntegerField(default=0),
        ),
    ]
