# Generated by Django 4.0.3 on 2022-04-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captchaprot', '0005_challenges_choiceratio_alter_challenges_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opciones_reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=20)),
                ('cuenta', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=300)),
                ('eleccion', models.CharField(default='null', max_length=20)),
                ('umbral_eleccion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fiabilidad_eleccion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Challenges',
        ),
        migrations.AddField(
            model_name='opciones_reto',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captchaprot.reto'),
        ),
        migrations.AlterUniqueTogether(
            name='opciones_reto',
            unique_together={('reto', 'opcion')},
        ),
    ]
