# Generated by Django 4.0.3 on 2022-04-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captchaprot', '0006_opciones_reto_reto_delete_challenges_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opciones_reto',
            new_name='Opciones_retos',
        ),
        migrations.RenameModel(
            old_name='Reto',
            new_name='Retos',
        ),
    ]
