# Generated by Django 4.0.3 on 2022-04-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captchaprot', '0007_rename_opciones_reto_opciones_retos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opciones_retos',
            new_name='Opciones_reto',
        ),
        migrations.RenameModel(
            old_name='Retos',
            new_name='Reto',
        ),
    ]
