# Generated by Django 4.0.3 on 2022-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaprot', '0008_rename_opciones_retos_opciones_reto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reto',
            name='fiabilidad_eleccion',
        ),
        migrations.AddField(
            model_name='opciones_reto',
            name='fiabilidad_opcion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reto',
            name='cuenta_respuestas',
            field=models.BigIntegerField(default=0),
        ),
    ]
