# Generated by Django 4.0.3 on 2022-04-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaprot', '0009_remove_reto_fiabilidad_eleccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opciones_reto',
            name='fiabilidad_opcion',
        ),
        migrations.AddField(
            model_name='reto',
            name='fiabilidad_opcion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
