# Generated by Django 4.0.3 on 2022-04-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaprot', '0011_clave_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clave_usuario',
            name='clave',
            field=models.CharField(max_length=32),
        ),
    ]
